.PHONY: backend
backend:
	./create_backend.sh

.PHONY: init
init:
	terraform init

.PHONY: fmt
fmt:
	terraform fmt --recursive

.PHONY: plan
plan:
	terraform plan

.PHONY: apply
apply:
	terraform apply

