name: pull-dev
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_DEV }}
          aws-region: ap-northeast-1
      - name: terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          terraform-home-directory: terraform
          terraform-exec-directory: terraform/aws/environments/dev
          terraform-version: 1.3.7
